-- CreateTable
CREATE TABLE "OrgAccountSetting" (
    "id" INTEGER NOT NULL,
    "settings" JSONB NOT NULL,
    "enableSerializedInventory" BOOLEAN,
    "enableGroupedProducts" BOOLEAN,
    "scanBundleItems" BOOLEAN,
    "generateBarcodeByName" BOOLEAN,
    "generateBarcodeBySeries" BOOLEAN,
    "generateSkuByName" BOOLEAN,
    "generateSkuBySeries" BOOLEAN,
    "barcodePrefix" TEXT,
    "skuPrefix" TEXT,
    "startingSeqNum" INTEGER,
    "attrCharLength" INTEGER,
    "keepSellingOnOutOfStock" BOOLEAN,
    "continueTransferOnOutOfStock" BOOLEAN,
    "printSkuOnDocuments" BOOLEAN,
    "printBarcodeOnDocuments" BOOLEAN,
    "verifyItemsBeforeFulfill" BOOLEAN,
    "barcodeLabelWidth" DOUBLE PRECISION,
    "barcodeLabelHeight" DOUBLE PRECISION,
    "barcodeWidth" DOUBLE PRECISION,
    "barcodeHeight" DOUBLE PRECISION,
    "barcodeLabelLeftPadding" DOUBLE PRECISION,
    "barcodeLabelGap" DOUBLE PRECISION,
    "printProductName" BOOLEAN,
    "printVariantName" BOOLEAN,
    "printRetailPrice" BOOLEAN,
    "printSKU" BOOLEAN,
    "printProductAttributes" BOOLEAN,
    "barcodeLabelColumns" INTEGER,
    "multipelUoms" BOOLEAN,
    "taxInclusive" BOOLEAN,
    "gst" TEXT,
    "fbrPCTCode" TEXT,
    "enableCustomOrderStages" BOOLEAN,
    "maxDiscountForReturn" DOUBLE PRECISION,
    "paymentDueAlert" BOOLEAN,
    "lastPaymentAlert" BOOLEAN,
    "lockAccount" BOOLEAN,
    "autoOrderDiscount" DOUBLE PRECISION,
    "enableMto" BOOLEAN,
    "maxAllowedRefund" DOUBLE PRECISION,
    "courierServiceSelection" BOOLEAN,
    "currencyCode" TEXT,
    "organizationContent" TEXT,
    "printPackingList" BOOLEAN,
    "isMultiVendor" BOOLEAN,
    "vendorName" TEXT,
    "pickListSmall" BOOLEAN,
    "useMtoImages" BOOLEAN,
    "askForCustomer" BOOLEAN,
    "askForSalesPerson" BOOLEAN,
    "enablePosOrderSeq" BOOLEAN,
    "enablePurchaseOrderTypes" BOOLEAN,
    "maxSubOrders" INTEGER,
    "softAdjustmentOpeningDate" TIMESTAMP(3),
    "compactShippingLabel" BOOLEAN,
    "enablePickerAssignment" BOOLEAN,
    "enableSaleOrderAssignment" BOOLEAN,
    "saleOrderReAssignment" BOOLEAN,
    "enableAccountCodes" BOOLEAN,
    "invoiceControlPaymentAccountId" INTEGER,
    "invoiceControlPaymentAccountName" TEXT,
    "defaultPriceList" TEXT,
    "shippingLabelDocumentId" INTEGER,
    "shippingLabelDocumentDescription" BOOLEAN,
    "shippingLabelDocumentProductName" BOOLEAN,
    "shippingLabelDocumentProductSku" BOOLEAN,
    "shippingLabelDocumentRemarks" BOOLEAN,
    "shippingLabelDocumentPrintBarcode" BOOLEAN,
    "shippingLabelDocumentNumOfLabels" INTEGER,
    "shippingLabelDocumentSortLabelBySku" BOOLEAN,
    "shippingLabelDocumentDefaultRemarks" TEXT,
    "stockAllocationRules" BOOLEAN,
    "isDropShippingAccount" BOOLEAN,
    "enableMultiLocationFulfillment" BOOLEAN,
    "applyThreeLevelBuffer" BOOLEAN,
    "fbrPosFeeOnlineOrders" DOUBLE PRECISION,
    "isCustomerRequired" BOOLEAN,
    "isSalesPersonRequired" BOOLEAN,
    "showCustomerSelectionAlert" BOOLEAN,
    "disableManualBarcodeEntryInDispatch" BOOLEAN,
    "manualCompletionInDispatch" BOOLEAN,
    "syncDraftQuantityToExternalApps" BOOLEAN,
    "splitFulfillment" BOOLEAN,
    "distanceOptimisedFulfillment" BOOLEAN,
    "maxDistanceForFullOrderFulfillment" INTEGER,
    "useSequenceBarcoding" BOOLEAN,
    "duplicateResolutionLimit" INTEGER,
    "receivePurchaseOrderByGrn" BOOLEAN,
    "productionOrderScanning" BOOLEAN,
    "useRevisedShippingLabel" BOOLEAN,
    "allowManualQtyInScan" BOOLEAN,
    "autoReplaceErrorCodeInDispatch" BOOLEAN,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OrgAccountSetting_pkey" PRIMARY KEY ("id")
);
